version: '3.3'

services:
  dev_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: grey_unicorn_sticky_notes
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grey_unicorn_sticky_notes_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
